---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
#  namespace: maria-name
data:
  password: MTIzNA== # base64로 인코딩 된 pw 1234 값 입력
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: maria-name
data:
  password: YWJjZGVmZ2hpamtsbW5vcDEyMzQ1NjU0Nzg=  # base64로 인코딩 된 pw 1234 값 입력