apiVersion: apps/v1
kind: Deployment # pod 여러개
metadata:
  name: order-service-deployment
spec: # 어떻게 만들지 대한 내용
  replicas: 1 # 몇개의 pod 만들래?
  selector:
    matchLabels:
      app: order-service # 쿠버네티스 안에서 변수명
  template:
    metadata:
      labels:
        app: order-service # 서비스에서 찾는 변수명
    spec: # pod 하나하나에 대한 내용
      containers:
        - name: order-service
          image: parkmyounghoi/order-service:msa.k8.06  # dockerhub 에 있는 image
#          imagePullPolicy: Always # 매번 이미지를 가져오도록 설정

          ports:
            - containerPort: 40004 #default one
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: spring-datasource-url-order
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: spring-datasource-username
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: order-service-port
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: management-zipkin-tracing-endpoint
            - name: FIRST_SERVICE_URL
              value: first-service:40001
            - name: ORDER_SERVICE_URL
              value: order-service:40004
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: spring-kafka-bootstrap-servers

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: LoadBalancer
  ports:
    - port: 40004
      targetPort: 40004
  selector:
    app: order-service